# Generated by Django 4.2.21 on 2026-07-06 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email_ciphertext",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                (
                    "email_bidx",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "name_ciphertext",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                (
                    "institution_ciphertext",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                (
                    "country_ciphertext",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                (
                    "faculty_ciphertext",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                (
                    "research_level_ciphertext",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("funded", models.BooleanField(blank=True, null=True)),
                ("mailing_list", models.BooleanField(blank=True, null=True)),
                ("admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("failed_attempts", models.IntegerField(default=0)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("sign_in_count", models.IntegerField(default=0)),
                ("current_sign_in_at", models.DateTimeField(blank=True, null=True)),
                ("last_sign_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_sign_in_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "last_sign_in_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "reset_password_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("reset_password_sent_at", models.DateTimeField(blank=True, null=True)),
                ("remember_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "unlock_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="ResearcherInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_code", models.CharField(max_length=255, unique=True)),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "researcher_invitations",
            },
        ),
    ]
