# Generated by Django 4.2.21 on 2026-07-06 11:01

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experiments", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.IntegerField()),
                (
                    "answer_ciphertext",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="tasks.question",
                    ),
                ),
            ],
            options={
                "db_table": "responses",
            },
        ),
        migrations.CreateModel(
            name="ParticipantId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.IntegerField()),
                (
                    "email_ciphertext",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("email_bidx", models.CharField(blank=True, default="", max_length=64)),
                ("slug", models.CharField(blank=True, max_length=32, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_ids",
                        to="experiments.experiment",
                    ),
                ),
            ],
            options={
                "db_table": "participant_ids",
            },
        ),
        migrations.CreateModel(
            name="ClickResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.IntegerField()),
                ("time", models.FloatField(blank=True, null=True)),
                (
                    "answer_ciphertext",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, null=True
                    ),
                ),
                ("no_clicks_explanation", models.BooleanField(default=False)),
                ("from_checkbox", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "click_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_responses",
                        to="tasks.clicktask",
                    ),
                ),
            ],
            options={
                "db_table": "click_responses",
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.IntegerField()),
                ("visited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "visits",
                "unique_together": {("participant_id", "task")},
            },
        ),
    ]
