# Generated by Django 4.2.21 on 2026-07-06 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experiments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Free text"),
                            ("checkbox", "Checkboxes"),
                            ("radio", "Radio buttons"),
                            ("dropdown", "Dropdown"),
                            ("rating", "Rating scale"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(blank=True, default="")),
                ("sort", models.IntegerField(blank=True, null=True)),
                ("required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "questions",
                "ordering": ["sort"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sort", models.IntegerField(blank=True, null=True)),
                ("random", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="experiments.experiment",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["sort"],
            },
        ),
        migrations.CreateModel(
            name="ClickTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.task",
                    ),
                ),
                ("prompt", models.TextField(blank=True, null=True)),
                ("explanation_prompt", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "click_tasks",
            },
            bases=("tasks.task",),
        ),
        migrations.CreateModel(
            name="IntermediateScreenTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.task",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "intermediate_screen_tasks",
            },
            bases=("tasks.task",),
        ),
        migrations.CreateModel(
            name="ListeningTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.task",
                    ),
                ),
                (
                    "listens",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "db_table": "listening_tasks",
            },
            bases=("tasks.task",),
        ),
        migrations.CreateModel(
            name="QuestionTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "question_tasks",
            },
            bases=("tasks.task",),
        ),
        migrations.CreateModel(
            name="SampleTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.task",
                    ),
                ),
                ("calibration", models.BooleanField(default=False)),
                ("audio", models.FileField(blank=True, null=True, upload_to="audio/")),
                (
                    "transcript",
                    models.FileField(blank=True, null=True, upload_to="transcripts/"),
                ),
            ],
            options={
                "db_table": "sample_tasks",
            },
            bases=("tasks.task",),
        ),
        migrations.CreateModel(
            name="Scale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bins",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                ("low", models.CharField(blank=True, default="", max_length=255)),
                ("high", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        limit_choices_to={"question_type": "rating"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scale",
                        to="tasks.question",
                    ),
                ),
            ],
            options={
                "db_table": "scales",
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contents", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="tasks.question",
                    ),
                ),
            ],
            options={
                "db_table": "options",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="sample_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="tasks.sampletask",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="tasks.questiontask",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("experiment__isnull", False), ("sample_task__isnull", True)
                    ),
                    models.Q(
                        ("experiment__isnull", True), ("sample_task__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="task_has_exactly_one_owner",
            ),
        ),
    ]
