# Generated by Django 4.2.21 on 2026-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text question"),
                    ("checkbox", "Checkboxes"),
                    ("radio", "Radio buttons"),
                    ("dropdown", "Dropdown box"),
                    ("rating", "Rating scale"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
